config/routes.rb
KeymailExample::Application.routes.draw do

  root 'messages#index'

  resource :messages

  post 'send_keymail',  to: 'sessions#send_keymail'
  get  'auth/:url_key', to: 'sessions#verify_link', as: 'keymail_link_target'
  get 'log_out',        to: 'sessions#log_out'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user
  validates_presence_of :text

  delegate :email, to: :user, prefix: true

  scope :newest_first, -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true

  before_create :generate_auth_token

  def generate_auth_token
    begin
      self.auth_token = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: self.auth_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(auth_token: cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def authorize!
    head :unauthorized if current_user.nil?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authorize!, except: [:index]

  def index
    @messages = Message.newest_first.page(params[:page])
    @new_message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user

    if @message.save
      flash[:notice] = 'Message successfully posted!'
    else
      # TODO: should use real error messages, but there really isn't much else that can happen
      flash[:error] = 'Message cannot be empty.'
    end
    redirect_to root_path
  end

  def destroy
    Message.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def send_keymail
    begin
      Keymail::Authentication.request(params[:email])
      flash[:notice] = "An email has been sent to #{params[:email]}, click the link in the email to log in."
    rescue
      flash[:error] = "Something went wrong when trying to send keymail."
    end
    redirect_to root_path
  end

  def verify_link
    result = Keymail::Authentication.verify_url_key(params[:url_key])

    if result.authenticated?
      login_or_register_user(result.email)
      flash[:success] = 'Successfully logged in'
      redirect_to root_path
    else
      flash[:error] = 'Login failed'
      redirect_to root_path
    end
  end

  def log_out
    cookies.delete(:auth_token)
    flash[:notice] = 'Logged out successfully'
    redirect_to root_path
  end

  private

  def login_or_register_user(email)
    user = User.where(email: email).first_or_create
    persist_login(user)
  end

  def persist_login(user)
    cookies.permanent[:auth_token] = user.auth_token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(flash_type)
    map = {
      notice: 'info',
      success: 'success',
      error: 'danger',
      alert: 'warning'

    }
    unless map[flash_type].nil?
      "alert alert-#{map[flash_type]}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KeymailExample</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <header>
    <h1>Keymail example</h1>
    <p>This is an example application that demonstrates <%= link_to 'Keymail', 'https://github.com/alcesleo/keymail' %>, here is the <%= link_to 'source', 'https://github.com/alcesleo/keymail-example' %>.</p>
  </header>

  <% flash.each do |type, message| %>
    <div class="<%= flash_class(type) %>"><%= message %></div>
  <% end %>

  <div class="user-info">
    <% if current_user %>
      <p>
        You are currently logged in as <strong><%= current_user.email %></strong>. Type a message below or
        <%= link_to 'Log out', log_out_path, class: 'btn btn-danger btn-xs' %>.
      </p>
    <% elsif %>
      <p>Please log in by entering your email and pressing <strong>enter</strong>, then click the link that will be emailed to you.</p>
    <% end %>
  </div>

  <% unless current_user %>
    <%= render 'shared/authentication_form' %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @new_message do |f| %>
    <%= f.text_field :text, placeholder: 'Your message', class: 'form-control' %>
<% end %>

app/views/messages/index.html.erb
<% if current_user %>
  <%= render 'form' %>
<% end %>

<% @messages.each do |message| %>
  <div class="well clearfix">
    <p class="pull-left"><span class="glyphicon glyphicon-comment"></span> <%= message.text %></p>

      <aside class="pull-right">
        <span class="glyphicon glyphicon-user"></span> <%= message.user_email %> |
        <span class="glyphicon glyphicon-time"></span> <%= time_tag(message.created_at) %>
      </aside>
  </div>
<% end %>

<%= paginate @messages %>

app/views/shared/_authentication_form.html.erb
<%= form_tag send_keymail_path do |f| %>
    <%= text_field_tag :email, nil, placeholder: 'Log in with email', class: 'form-control' %>
<% end %>